# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Air JorDan
email: chrrkrrhsen@gmail.com
author: HyeokJun Gil
description: Try to use Git / Github
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2021 HyeokJun Gil. All Rights Reserved.'
credits: 'Credits: This blog is intended for open source assignments.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100006563046246
  - title: github
    url: https://github.com/mac-hz97
  - title: instagram
    url: https://www.instagram.com/khyeokjun2/
